### ISSUE TITLE
[Error Correction]: DL/Assignment 1 /Assignment 1.ipynb

### ISSUE THREAD

**Issue by alok-marathe** [NotShrirang/SPPU-Assignments#1]
In line 59, the shape argument should be a tuple `shape = (3,)`
You can refer to [this](https://www.tensorflow.org/api_docs/python/tf/keras/Input) documentation:
> shape | A shape tuple (tuple of integers or None objects), not including the batch size. For instance, shape=(32,) indicates that the expected input will be batches of 32-dimensional vectors. Elements of this tuple can be None; None elements represent dimensions where the shape is not known and may vary (e.g. sequence length).

**Comment by NotShrirang** [comment]
Hey @alok-marathe,
Please check. I have fixed it now.
Thanks for pointing it out!

**Comment by atharvabhide** [comment]
hello I am under the water....
